name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
      - name: Check Telegram API (for debugging)
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "chat_id": "${{ secrets.TELEGRAM_TO }}", 
            "text": "Test from Direct API"
          }' "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage"
        continue-on-error: true 

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}  
          token: ${{ secrets.TELEGRAM_TOKEN }} 
          message: |
            The ${{ github.event_name }} event triggered.
            This event is a push to the main branch. # More appropriate message
      
  report-genertion:
    runs-on: ubuntu-latest
    steps:
      - name: Generate text report
        run: |
          echo "GitHub Actions Report" > report.txt
          echo "----------------------" >> report.txt
          echo "Event: ${{ github.event_name }}" >> report.txt
          echo "Repository: ${{ github.repository }}" >> report.txt
          echo "Commit SHA: ${{ github.sha }}" >> report.txt
          echo "Commit Message:" >> report.txt
          echo "Build Status: Success (replace with actual status)" >> report.txt
          echo "----------------------" >> report.txt
      
      - name: upload generated artifacts
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.txt
         

# 8111880171:AAFi9XLnYjrUeZeP4nenSRcCb3ZNKdPp7OE
# telegram_bot:tle
