name: Manual Trigger with Approval

on:
  workflow_dispatch:  # Allows manual trigger
    
jobs:
  request-approval:
    runs-on: ubuntu-latest
    environment: manual-approval  # This enforces approval before execution
    steps:
      - name: Log Approver Name
        run: echo "This workflow was approved by team member ${{ github.actor }}"
      - name: Print message
        run: echo "Workflow the is running after approval!"